apiVersion: v1
kind: Pod
metadata:
  name: samplego
  labels:
     app: samplego
spec:
  containers:
    - image: sumithknowit/samplego:v3
      imagePullPolicy: Always
      name: samplego
      ports:
      - containerPort: 8080
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: samplego
spec:
  selector:
    app: samplego
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: samplego-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /samplego
          pathType: Prefix
          backend:
            service:
              name: samplego
              port:
                number: 80
