apiVersion: v1
kind: Pod
metadata:
  labels:
    run: samplego
  name: samplego
spec:
  containers:
    - image: sumithknowit/samplego:v3
      imagePullPolicy: Always
      name: samplego
---
apiVersion: v1
kind: Service
metadata:
  name: samplego
  #namespace: samplego
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: samplego
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: samplego-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /samplego
          pathType: Prefix
          backend:
            service:
              name: samplego
              port:
                number: 80
